const STORAGE='carvora-v2-state';
const $=id=>document.getElementById(id);const today=()=>new Date().toISOString().slice(0,10);const clone=v=>JSON.parse(JSON.stringify(v));
const blankVehicle=()=>({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()+Math.random()),make:'',model:'',year:'',mileage:'',fuel:'Petrol',purchasePrice:0,costs:{fuel:150,service:60,insurance:75,other:0,annualKm:12000},maintenance:[]});
const defaultState={vehicles:[blankVehicle()],activeId:null,savedAt:null};let state=load();if(!state.activeId)state.activeId=state.vehicles[0]?.id;
function load(){try{const raw=JSON.parse(localStorage.getItem(STORAGE)||'{}');if(Array.isArray(raw.vehicles))return {...raw,vehicles:raw.vehicles.map(v=>({...blankVehicle(),...v,costs:{...blankVehicle().costs,...(v.costs||{})},maintenance:Array.isArray(v.maintenance)?v.maintenance:[]}))};return migrateOld()}catch{return clone(defaultState)}}
function migrateOld(){try{const raw=JSON.parse(localStorage.getItem('carvora-v1-state')||'{}');const v=blankVehicle();v.make=raw.vehicle?.make||'';v.model=raw.vehicle?.model||'';v.year=raw.vehicle?.year||'';v.mileage=raw.vehicle?.mileage||'';v.fuel=raw.vehicle?.fuel||'Petrol';v.purchasePrice=raw.vehicle?.purchasePrice||0;v.costs={...v.costs,...(raw.costs||{})};v.maintenance=raw.maintenance||[];return {vehicles:[v],activeId:v.id,savedAt:null}}catch{return clone(defaultState)}}
function current(){return state.vehicles.find(v=>v.id===state.activeId)||state.vehicles[0]}
function save(){state.savedAt=today();localStorage.setItem(STORAGE,JSON.stringify(state));render()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}function money(n){return '$'+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0})}function km(n){return Number(n||0).toLocaleString()+' km'}
function addMonths(date,months){const d=new Date(date+'T00:00:00');d.setMonth(d.getMonth()+Number(months||0));return d}
function maintenanceStatus(m){const v=current();const now=new Date();let dueKm=null,dueDate=null;if(Number(m.intervalKm)>0&&Number(m.mileage)>0)dueKm=Number(m.mileage)+Number(m.intervalKm);if(Number(m.intervalMonths)>0&&m.date)dueDate=addMonths(m.date,m.intervalMonths);const kmDue=dueKm!==null&&Number(v.mileage)>=dueKm;const dateDue=dueDate&&now>=dueDate;const kmSoon=dueKm!==null&&dueKm-Number(v.mileage)<=1000&&dueKm>=Number(v.mileage);const dateSoon=dueDate&&((dueDate-now)/86400000)<=30&&dueDate>=now;if(kmDue||dateDue)return'Overdue';if(kmSoon||dateSoon)return'Soon';return'OK'}
function dueLabel(m){const v=current();const parts=[];if(Number(m.intervalKm)>0&&Number(m.mileage)>0)parts.push(km(Number(m.mileage)+Number(m.intervalKm)));if(Number(m.intervalMonths)>0&&m.date)parts.push(addMonths(m.date,m.intervalMonths).toISOString().slice(0,10));return parts.length?parts.join(' / '):'No interval'}
function priorities(){const rank={Overdue:0,Soon:1};return current().maintenance.map((m,i)=>({m,i,status:maintenanceStatus(m)})).filter(x=>x.status!=='OK').sort((a,b)=>rank[a.status]-rank[b.status])}
function score(){const v=current();let s=100;const p=priorities();s-=p.filter(x=>x.status==='Overdue').length*15+p.filter(x=>x.status==='Soon').length*5;if(!v.make||!v.model||!v.year)s-=8;const miles=Number(v.mileage||0);if(miles>180000)s-=8;if(miles>250000)s-=8;const age=new Date().getFullYear()-Number(v.year||new Date().getFullYear());s-=Math.min(Math.max(age,0)*1.5,12);return Math.max(35,Math.min(100,Math.round(s)))}
function render(){const v=current();if(!v)return;safeSet('make',v.make);safeSet('model',v.model);safeSet('year',v.year);safeSet('mileage',v.mileage);safeSet('fuelType',v.fuel);safeSet('purchasePrice',v.purchasePrice);safeSet('activeVehicle',v.make&&v.model?`${v.make} ${v.model}`:'New vehicle');$('vehicleCount').textContent=`${state.vehicles.length} vehicle${state.vehicles.length===1?'':'s'}`;const s=score();$('score').textContent=s;$('scoreText').textContent=s>=85?'Strong baseline':s>=70?'Needs attention':'Service recommended';$('score').className='num '+(s>=85?'good':s>=70?'warn':'danger');$('scoreBar').style.width=s+'%';const p=priorities();$('priorityList').innerHTML=p.length?p.slice(0,5).map(x=>`<div class="row"><span><b>${x.status==='Overdue'?'Action':'Monitor'}</b> · ${esc(x.m.name)}<br><small class="muted">Due: ${esc(dueLabel(x.m))}</small></span><span class="status ${x.status==='Overdue'?'danger':'warn'}">${x.status}</span></div>`).join(''):'<div class="empty">No urgent maintenance items.</div>';$('priorityList2').innerHTML=p.length?p.slice(0,5).map(x=>`<div class="row"><span>${esc(x.m.name)}<br><small class="muted">Due: ${esc(dueLabel(x.m))}</small></span><span class="status ${x.status==='Overdue'?'danger':'warn'}">${x.status}</span></div>`).join(''):'<div class="empty">No flagged records. Your maintenance schedule is clear.</div>';$('maintenanceList').innerHTML=v.maintenance.length?v.maintenance.map((m,i)=>{const st=maintenanceStatus(m);return `<div class="row"><span><b>${esc(m.name)}</b><br><small class="muted">Serviced ${esc(m.date||'No date')} · ${km(m.mileage)} · ${money(m.cost)}</small><br><small class="muted">Next: ${esc(dueLabel(m))}${m.notes?' · '+esc(m.notes):''}</small></span><span class="rowActions"><span class="status ${st==='Overdue'?'danger':st==='Soon'?'warn':''}">${st}</span><button class="btn" onclick="editMaintenance(${i})">Edit</button><button class="btn" onclick="deleteMaintenance(${i})">Delete</button></span></div>`}).join(''):'<div class="empty">No records yet. Add your first service.</div>';const c=v.costs;const total=Number(c.fuel||0)+Number(c.service||0)+Number(c.insurance||0)+Number(c.other||0);$('monthly').textContent=money(total);$('annualCost').textContent=money(total*12);$('annualCost2').textContent=money(total*12);$('costPerKm').textContent=c.annualKm?money(total*12/Number(c.annualKm)):'—';$('nextService').textContent=p[0]?p[0].m.name:'No urgent items';fillCosts();renderGarage();renderAnalytics()}
function renderGarage(){$('garageList').innerHTML=state.vehicles.map(v=>`<button class="btn ${v.id===state.activeId?'primary':''}" onclick="switchVehicle('${v.id}')">${esc(v.make&&v.model?v.make+' '+v.model:'New vehicle')}</button>`).join('')+`<button class="btn" onclick="createVehicle()">+ New vehicle</button>`}
function renderAnalytics(){const v=current(),records=v.maintenance.length,spend=v.maintenance.reduce((a,m)=>a+Number(m.cost||0),0);$('recordCount').textContent=records;$('serviceSpend').textContent=money(spend);$('avgService').textContent=money(records?spend/records:0);$('analyticsText').textContent=records?`You have logged ${records} service record${records===1?'':'s'}, with ${money(spend)} recorded maintenance spend. Use intervals to keep future due dates visible.`:'Add service records to see maintenance spending patterns.'}
function safeSet(id,value){if($(id))$(id).value=value??''}function fillCosts(){const c=current().costs;safeSet('fuel',c.fuel);safeSet('service',c.service);safeSet('insurance',c.insurance);safeSet('other',c.other);safeSet('annualKm',c.annualKm)}
function saveVehicle(){const v=current(),year=Number($('year').value),mileage=Number($('mileage').value);if(!$('make').value.trim()||!$('model').value.trim())return toast('Enter make and model.');if(year<1950||year>2100)return toast('Enter a valid vehicle year.');if(mileage<0)return toast('Mileage cannot be negative.');Object.assign(v,{make:$('make').value.trim(),model:$('model').value.trim(),year,mileage,fuel:$('fuelType').value,purchasePrice:Number($('purchasePrice').value||0)});save();toast('Vehicle saved locally.')}
function createVehicle(){const v=blankVehicle();state.vehicles.push(v);state.activeId=v.id;save();scrollToId('vehicle');toast('New vehicle created.')}
function switchVehicle(id){state.activeId=id;save();toast('Vehicle switched.')}
function openMaintenance(i=null){$('maintenanceModal').classList.add('open');$('maintenanceModal').setAttribute('aria-hidden','false');$('mIndex').value=i??'';const m=i===null?{}:current().maintenance[i]||{};$('mName').value=m.name||'';$('mDate').value=m.date||today();$('mMileage').value=m.mileage||current().mileage||'';$('mIntervalKm').value=m.intervalKm||'';$('mIntervalMonths').value=m.intervalMonths||'';$('mCost').value=m.cost||'';$('mNotes').value=m.notes||'';$('mName').focus()}
function closeMaintenance(){$('maintenanceModal').classList.remove('open');$('maintenanceModal').setAttribute('aria-hidden','true')}function editMaintenance(i){openMaintenance(i)}function deleteMaintenance(i){if(confirm('Delete this maintenance record?')){current().maintenance.splice(i,1);save();toast('Record deleted.')}}
function saveMaintenance(){const item={name:$('mName').value.trim(),date:$('mDate').value,mileage:Number($('mMileage').value||0),intervalKm:Number($('mIntervalKm').value||0),intervalMonths:Number($('mIntervalMonths').value||0),cost:Number($('mCost').value||0),notes:$('mNotes').value.trim()};if(!item.name||!item.date)return toast('Enter a service name and date.');if(!item.intervalKm&&!item.intervalMonths)return toast('Add a km or month interval so CARVORA can calculate the next service.');const i=$('mIndex').value;i===''?current().maintenance.push(item):current().maintenance[Number(i)]=item;closeMaintenance();save();toast('Maintenance schedule saved.')}
function calculate(){const v=current();v.costs={fuel:Number($('fuel').value||0),service:Number($('service').value||0),insurance:Number($('insurance').value||0),other:Number($('other').value||0),annualKm:Number($('annualKm').value||0)};save();toast('Ownership cost updated.')}
function resetDemo(){if(!confirm('Replace your garage with a clean demo?'))return;const v=blankVehicle();Object.assign(v,{make:'Toyota',model:'Corolla',year:2021,mileage:62000,purchasePrice:18500,maintenance:[{name:'Oil & filter',date:'2026-09-01',mileage:58000,intervalKm:10000,intervalMonths:6,cost:55,notes:'Full synthetic oil'},{name:'Brake inspection',date:'2026-08-20',mileage:52000,intervalKm:10000,intervalMonths:12,cost:40},{name:'Tyre rotation',date:'2026-06-01',mileage:41500,intervalKm:10000,cost:25}]});state={vehicles:[v],activeId:v.id,savedAt:null};save();toast('Demo garage loaded.')}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='carvora-v2-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Backup exported.')}
function clearData(){if(confirm('Clear all CARVORA V2 data from this browser?')){localStorage.removeItem(STORAGE);state=clone(defaultState);state.activeId=state.vehicles[0].id;render();toast('Local data cleared.')}}function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');clearTimeout(window.__carvoraToast);window.__carvoraToast=setTimeout(()=>e.classList.remove('show'),1800)}
$('vehicleForm').addEventListener('submit',e=>{e.preventDefault();saveVehicle()});$('costForm').addEventListener('submit',e=>{e.preventDefault();calculate()});$('maintenanceForm').addEventListener('submit',e=>{e.preventDefault();saveMaintenance()});$('addMaintenance').onclick=()=>openMaintenance();$('cancelMaintenance').onclick=closeMaintenance;$('resetDemo').onclick=resetDemo;$('exportData').onclick=exportData;$('clearData').onclick=clearData;$('addVehicle').onclick=createVehicle;$('openCalc').onclick=()=>scrollToId('calculator');$('maintenanceModal').addEventListener('click',e=>{if(e.target.id==='maintenanceModal')closeMaintenance()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMaintenance()});function scrollToId(id){$(id).scrollIntoView({behavior:'smooth',block:'start'})}render();