const STORAGE='carvora-v1-state';
const $=id=>document.getElementById(id);
const today=()=>new Date().toISOString().slice(0,10);
const defaultState={vehicle:{make:'',model:'',year:'',mileage:'',fuel:'Petrol',purchasePrice:''},maintenance:[],costs:{fuel:150,service:60,insurance:75,other:0,annualKm:12000},savedAt:null};
let state=load();
function clone(v){return JSON.parse(JSON.stringify(v))}
function load(){try{const raw=JSON.parse(localStorage.getItem(STORAGE)||'{}');return {...clone(defaultState),...raw,vehicle:{...defaultState.vehicle,...(raw.vehicle||{})},costs:{...defaultState.costs,...(raw.costs||{})},maintenance:Array.isArray(raw.maintenance)?raw.maintenance:[]}}catch{return clone(defaultState)}}
function save(){state.savedAt=today();localStorage.setItem(STORAGE,JSON.stringify(state));render()}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function km(n){return Number(n||0).toLocaleString()+' km'}
function money(n){return '$'+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:0})}
function maintenanceStatus(m){const current=Number(state.vehicle.mileage||0),serviceKm=Number(m.mileage||0),interval=Number(m.intervalKm||0);const dueKm=serviceKm+interval;const hasKmDue=interval>0&&serviceKm>0;const date=m.date?new Date(m.date+'T00:00:00'):null;const days=date?Math.ceil((date-new Date())/86400000):9999;if(hasKmDue&&current>dueKm)return'Overdue';if(hasKmDue&&dueKm-current<=1000)return'Soon';if(date&&days<0)return'Overdue';if(date&&days<=30)return'Soon';return'OK'}
function score(){let s=100;const overdue=state.maintenance.filter(m=>maintenanceStatus(m)==='Overdue').length,soon=state.maintenance.filter(m=>maintenanceStatus(m)==='Soon').length;s-=overdue*15+soon*5;if(!state.vehicle.make||!state.vehicle.model||!state.vehicle.year)s-=8;const miles=Number(state.vehicle.mileage||0);if(miles>180000)s-=8;if(miles>250000)s-=8;const age=new Date().getFullYear()-Number(state.vehicle.year||new Date().getFullYear());s-=Math.min(Math.max(age,0)*1.5,12);return Math.max(35,Math.min(100,Math.round(s)))}
function priorities(){const rank={Overdue:0,Soon:1};return state.maintenance.map((m,i)=>({m,i,status:maintenanceStatus(m)})).filter(x=>x.status!=='OK').sort((a,b)=>rank[a.status]-rank[b.status])}
function render(){const v=state.vehicle;safeSet('make',v.make);safeSet('model',v.model);safeSet('year',v.year);safeSet('mileage',v.mileage);safeSet('fuelType',v.fuel||'Petrol');safeSet('purchasePrice',v.purchasePrice);const s=score();$('score').textContent=s;$('scoreText').textContent=s>=85?'Strong baseline':s>=70?'Needs attention':'Service recommended';$('score').className='num '+(s>=85?'good':s>=70?'warn':'danger');$('scoreBar').style.width=s+'%';$('scoreBar').style.background=s>=85?'var(--accent)':s>=70?'var(--warn)':'var(--danger)';const p=priorities();$('priorityList').innerHTML=p.length?p.slice(0,4).map(x=>`<div class="row"><span><b>${x.status==='Overdue'?'Action':'Monitor'}</b> · ${esc(x.m.name)}</span><span class="status ${x.status==='Overdue'?'danger':'warn'}">${x.status}</span></div>`).join(''):'<div class="empty">No urgent maintenance items.</div>';$('priorityList2').innerHTML=p.length?p.slice(0,4).map(x=>`<div class="row"><span>${esc(x.m.name)}</span><span class="status ${x.status==='Overdue'?'danger':'warn'}">${x.status}</span></div>`).join(''):'<div class="empty">No urgent maintenance items. Your car has no flagged records.</div>';$('maintenanceList').innerHTML=state.maintenance.length?state.maintenance.map((m,i)=>{const st=maintenanceStatus(m);return `<div class="row"><span><b>${esc(m.name)}</b><br><small class="muted">${esc(m.date||'No date')} · ${km(m.mileage)} · ${money(m.cost)}</small>${m.intervalKm?`<br><small class="muted">Repeat: ${km(m.intervalKm)}</small>`:''}${m.notes?`<br><small class="muted">${esc(m.notes)}</small>`:''}</span><span class="rowActions"><span class="status ${st==='Overdue'?'danger':st==='Soon'?'warn':''}">${st}</span><button class="btn" onclick="editMaintenance(${i})">Edit</button><button class="btn" onclick="deleteMaintenance(${i})">Delete</button></span></div>`}).join(''):'<div class="empty">No records yet. Add your first service.</div>';const c=state.costs;const total=Number(c.fuel||0)+Number(c.service||0)+Number(c.insurance||0)+Number(c.other||0);$('monthly').textContent=money(total);$('annualCost').textContent=money(total*12);$('costPerKm').textContent=c.annualKm?money(total*12/Number(c.annualKm)):'—';$('nextService').textContent=p[0]?p[0].m.name:'No urgent items';$('ownership').textContent=v.purchasePrice?money(v.purchasePrice):'Not set';$('total').textContent=money(total);fillCosts()}
function safeSet(id,value){if($(id))$(id).value=value??''}
function saveVehicle(){const year=Number($('year').value),mileage=Number($('mileage').value);if(year<1950||year>2100)return toast('Enter a valid vehicle year.');if(mileage<0)return toast('Mileage cannot be negative.');state.vehicle={make:$('make').value.trim(),model:$('model').value.trim(),year,mileage,fuel:$('fuelType').value,purchasePrice:Number($('purchasePrice').value||0)};save();toast('Vehicle saved locally.')}
function openMaintenance(i=null){$('maintenanceModal').classList.add('open');$('maintenanceModal').setAttribute('aria-hidden','false');$('mIndex').value=i??'';const m=i===null?{}:state.maintenance[i]||{};$('mName').value=m.name||'';$('mDate').value=m.date||today();$('mMileage').value=m.mileage||state.vehicle.mileage||'';$('mIntervalKm').value=m.intervalKm||'';$('mCost').value=m.cost||'';$('mNotes').value=m.notes||'';$('mName').focus()}
function closeMaintenance(){$('maintenanceModal').classList.remove('open');$('maintenanceModal').setAttribute('aria-hidden','true')}
function editMaintenance(i){openMaintenance(i)}
function deleteMaintenance(i){if(confirm('Delete this maintenance record?')){state.maintenance.splice(i,1);save();toast('Record deleted.')}}
function saveMaintenance(){const item={name:$('mName').value.trim(),date:$('mDate').value,mileage:Number($('mMileage').value||0),intervalKm:Number($('mIntervalKm').value||0),cost:Number($('mCost').value||0),notes:$('mNotes').value.trim()};if(!item.name)return toast('Enter a service name.');const i=$('mIndex').value;i===''?state.maintenance.push(item):state.maintenance[Number(i)]=item;closeMaintenance();save();toast('Maintenance saved.')}
function calculate(){state.costs={fuel:Number($('fuel').value||0),service:Number($('service').value||0),insurance:Number($('insurance').value||0),other:Number($('other').value||0),annualKm:Number($('annualKm').value||0)};save();toast('Ownership cost updated.')}
function fillCosts(){safeSet('fuel',state.costs.fuel);safeSet('service',state.costs.service);safeSet('insurance',state.costs.insurance);safeSet('other',state.costs.other);safeSet('annualKm',state.costs.annualKm)}
function resetDemo(){if(confirm('Replace current data with a clean demo vehicle?')){state={...clone(defaultState),vehicle:{...defaultState.vehicle,make:'Toyota',model:'Corolla',year:2021,mileage:62000,purchasePrice:18500},maintenance:[{name:'Oil & filter',date:'2026-09-01',mileage:58000,intervalKm:10000,cost:55,notes:'Full synthetic oil'},{name:'Brake inspection',date:'2026-08-20',mileage:52000,intervalKm:10000,cost:40},{name:'Tyre rotation',date:'2026-06-01',mileage:41500,intervalKm:10000,cost:25}]};save();toast('Demo data loaded.')}}
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='carvora-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Backup exported.')}
function clearData(){if(confirm('Clear all CARVORA data from this browser?')){localStorage.removeItem(STORAGE);state=clone(defaultState);render();toast('Local data cleared.')}}
function toast(t){const el=$('toast');el.textContent=t;el.classList.add('show');clearTimeout(window.__carvoraToast);window.__carvoraToast=setTimeout(()=>el.classList.remove('show'),1800)}
$('vehicleForm').addEventListener('submit',e=>{e.preventDefault();saveVehicle()});$('costForm').addEventListener('submit',e=>{e.preventDefault();calculate()});$('maintenanceForm').addEventListener('submit',e=>{e.preventDefault();saveMaintenance()});$('addMaintenance').onclick=()=>openMaintenance();$('cancelMaintenance').onclick=closeMaintenance;$('resetDemo').onclick=resetDemo;$('exportData').onclick=exportData;$('clearData').onclick=clearData;$('addVehicle').onclick=()=>scrollToId('vehicle');$('openCalc').onclick=()=>scrollToId('calculator');$('maintenanceModal').addEventListener('click',e=>{if(e.target.id==='maintenanceModal')closeMaintenance()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMaintenance()});function scrollToId(id){$(id).scrollIntoView({behavior:'smooth',block:'start'})}
render();